#!/bin/zsh
function get_file() {
	ext=$1
	git ls-files '*.'${ext} | grep -v "^thirdparty/.*" | grep -v "^generated/.*"
}
{
	for ext in {'[ch]pp','[ch]',py,js,cmake,vim,pss,ptype,rs}
	do
		if [ ! -z "$(get_file ${ext})" ]
		then
			wc -l $(get_file ${ext}) | tail -n 1 | awk '{print "'${ext}'",$1}'
		fi
	done 
	for file in $(git ls-files misc/script/)
	do
		ftype=""
		if [ ! -z "$(head -n1 ${file} | grep "pscript")" ]
		then
			ftype="pss"
		fi
		if [ ! -z "$(head -n1 ${file} | grep "python")" ]
		then
			ftype="py"
		fi
		if [ ! -z "${ftype}" ]
		then
			echo "${ftype} $(wc -l ${file} | tail -n 1 | awk '{print $1}')"
		fi
	done
}| \
awk \
'
	BEGIN {
		name["[ch]pp"] = "C++";
		name["[ch]"] = "C";
		name["py"] = "Python"
		name["js"] = "JS"
		name["cmake"] = "CMake"
		name["vim"] = "Vim"
		name["pss"] = "PScript"
		name["ptype"] = "TypeDef" 
		name["rs"] = "Rust"
	}
	{
		sum += $2; 
		lang[$1] += $2
	} 
	END {
		for(i in lang) 
			print name[i]"\t"lang[i]"\t"lang[i]*100/sum"%"
		print "Total\t"sum"\t100%"
	}' | \
sort -nk 2  
