#!/bin/zsh
function get_file() {
	ext=$1
	git ls-files '*.'${ext} | grep -v "^thirdparty/.*"
}
for ext in {'[ch]pp','[ch]',py,js,cmake,vim,pss,ptype}
do
	if [ ! -z "$(get_file ${ext})" ]
	then
		wc -l $(get_file ${ext}) | tail -n 1 | awk '{print "'${ext}'",$1}'
	fi
done | \
awk \
'
	BEGIN {
		name["[ch]pp"] = "C++";
		name["[ch]"] = "C";
		name["py"] = "Python"
		name["js"] = "JS"
		name["cmake"] = "CMake"
		name["vim"] = "Vim"
		name["pss"] = "PScript"
		name["ptype"] = "TypeDef" 
	}
	{
		sum += $2; 
		lang[$1] = $2
	} 
	END {
		for(i in lang) 
			print name[i]"\t"lang[i]"\t"lang[i]*100/sum"%"
		print "Total\t"sum"\t100%"
	}' | \
sort -nk 2  
