find_package(PkgConfig)
pkg_check_modules(PC_UUID uuid)
if("${PC_UUID_FOUND}" STREQUAL "1")
	set(LOCAL_INCLUDE ${PC_UUID_INCLUDE_DIRS})
	set(LOCAL_LIBS pstd proto ${PC_UUID_LIBRARIES})
else("${PC_UUID_FOUND}" STREQUAL "1")
	message("Missing libjson-c, json_parser servlet disabled")
	set(build_restcon "no")
endif("${PC_UUID_FOUND}" STREQUAL "1")
set(INSTALL yes)
