set(TYPE shared-library)
set(LOCAL_CFLAGS "-fPIC")
set(LOCAL_LIBS plumber pservlet)
set(LOCAL_SOURCE types)
set(INSTALL "yes")
install_includes("${SOURCE_PATH}/include" "include/pstd" "*.h")
install_plumber_headers("include/pstd")
