set(TYPE shared-library)
set(LOCAL_CFLAGS "-fPIC")
set(LOCAL_LIBS pservlet proto)
set(LOCAL_SOURCE types)
set(INSTALL "yes")
set(PACKAGE_CONF_INSTALL_PATH "include/pstd")
install_includes("${SOURCE_PATH}/include" "include/pstd" "*.h")
install_plumber_headers("include/pstd")
