language: c
compiler: 
    - gcc-5
    - clang

os:
    - linux

env:
    - L=0 O=5 SANITIZER=no
    - L=6 O=5 SANITIZER=no
    - L=0 O=5 SANITIZER=yes LIBS=-fuse-ld=gold
    - L=6 O=5 SANITIZER=yes LIBS=-fuse-ld=gold

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - valgrind
            - libcurl3
            - cmake
            - g++
            - uuid-dev
            - pkg-config
            - libpython2.7-dev
            - libreadline-dev
            - libssl-dev
            - wget
            - git
            - libc++-dev
            - gcc-5
            - g++-5
before_install:
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew update; fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install cmake python pkg-config openssl ossp-uuid readline; fi
script:
    - lsb_release -a && cmake . && make && make test

