language: c
compiler: 
    - gcc
    - clang

os:
    - linux
    - osx

env:
    - L=0 O=5 SANITIZER=no
    - L=6 O=5 SANITIZER=no
    - L=0 O=5 SANITIZER=yes
    - L=6 O=5 SANITIZER=yes

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - valgrind
            - libcurl3
            - cmake
            - g++
            - uuid-dev
            - pkg-config
            - libpython2.7-dev
            - libreadline-dev
            - libssl-dev
            - wget
            - git
            - libc++-dev
            - gcc-5
            - g++-5

before_install:
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew update; fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install ossp-uuid; fi
    - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo rm /usr/bin/{gcc,g++}; sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc; sudo ln -s /usr/bin/g++-5 /usr/bin/g++; fi
    - if [[ "${SANITIZER}" == "yes" && "${CC}" == "gcc" ]]; then export LIBS="-fuse-ld=gold"; fi

script:
    - cmake . && make && make test

