language: c
compiler: 
    - gcc
    - clang

os:
    - linux
#   - osx

env:
    - L=6 O=5
    - L=0 O=5

#apt-get install -y  --allow-unauthenticated git cmake gcc g++ uuid-dev libssl-dev doxygen pkg-config python2.7 libpython2.7-dev libreadline-dev zsh
addons:
    apt:
        sourceline: 0k53d-karl-f830m/openssl
        packages:
            - libcurl3
            - cmake
            - g++
            - uuid-dev
            - pkg-config
            - libpython2.7-dev
            - libreadline-dev
            - libssl-dev
            - wget
            - git
before_install:
    - apt-get update && apt-get upgrade -y
script:
    - lsb_release -a && cmake . && make && make test

