language: c
compiler: 
    - gcc
    - clang

os:
    - linux
#    - osx

env:
    - L=6 O=5
    - L=0 O=5

#apt-get install -y  --allow-unauthenticated git cmake gcc g++ uuid-dev libssl-dev doxygen pkg-config python2.7 libpython2.7-dev libreadline-dev zsh
addons:
    apt:
        packages:
            - valgrind
            - libcurl3
            - cmake
            - g++
            - uuid-dev
            - pkg-config
            - libpython2.7-dev
            - libreadline-dev
            - libssl-dev
            - wget
            - git
            - libc++-dev
before_install:
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew update; fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install cmake python pkg-config openssl ossp-uuid readline; fi
script:
    - lsb_release -a && cmake . && make && make test

