find_package(PkgConfig)
if(NOT "${RAPIDJSON_DIR}" STREQUAL "RAPIDJSON_DIR-NOTFOUND")
	list(APPEND LOCAL_INCLUDE ${RAPIDJSON_DIR})
	list(APPEND LOCAL_LIBS pstd proto)
else(NOT "${RAPIDJSON_DIR}" STREQUAL "RAPIDJSON_DIR-NOTFOUND")
	message("Missing RapidJSON, json_parser servlet disabled")
	set(build_typing_conversion_json "no")
endif(NOT "${RAPIDJSON_DIR}" STREQUAL "RAPIDJSON_DIR-NOTFOUND")
set(INSTALL yes)
