set(TYPE static-library)
set(LOCAL_SOURCE comp)
set(PACKAGE_CONF_INSTALL_PATH "include/pss")
set(INSTALL "yes")
install_includes("${SOURCE_PATH}/include" "include/pss" "*.h")
install_includes("${CMAKE_SOURCE_DIR}/include/" "include/pss" "error.h")
install_includes("${CMAKE_SOURCE_DIR}/include/utils/" "include/pss/utils" "static_assertion.h")
install_includes("${CMAKE_SOURCE_DIR}/include/utils/" "include/pss/utils" "log_macro.h")
install_plumber_headers("include/pss")
