find_package(PkgConfig)
pkg_check_modules(PC_JSON json-c)
if("x${PC_JSON_FOUND}" STREQUAL "x1")
	set(LOCAL_INCLUDE ${PC_JSON_INCLUDE_DIRS})
	set(LOCAL_LIBS pstd proto ${PC_JSON_LIBRARIES})
else("x${PC_JSON_FOUND}" STREQUAL "x1")
	message("Missing libjson-c, json_parser servlet disabled")
	set(build_json_parse "no")
endif("x${PC_JSON_FOUND}" STREQUAL "x1")
set(INSTALL yes)
