if("${SYSNAME}" STREQUAL "Linux")
	find_package(PkgConfig)
	pkg_check_modules(PC_ZLIB zlib)
	if("${PC_ZLIB_FOUND}" STREQUAL "1")
		find_library(ZLIB_LIBRARIES NAMES ${PC_ZLIB_LIBRARIES} PATHS ${PC_ZLIB_LIBRARIES_DIRS})
		list(APPEND LOCAL_INCLUDE "${PC_ZLIB_INCLUDE_DIRS}")
		list(APPEND LOCAL_LIBS pstd proto "${ZLIB_LIBRARIES}")
	else("${PC_ZLIB_FOUND}" STREQUAL "1")
		message("Missing libcurl, network.http.encoder servlet won't build")
		set(build_network_http_encoder "no")
	endif("${PC_ZLIB_FOUND}" STREQUAL "1")
	set(INSTALL yes)
else("${SYSNAME}" STREQUAL "Linux")
	message("FIXME: network.http.encoder servlet only support Linux")
	set(build_network_http_client "no")
endif("${SYSNAME}" STREQUAL "Linux")
