if("${SYSNAME}" STREQUAL "Linux")
	find_package(PkgConfig)
	pkg_check_modules(PC_CURL libcurl)
	if("${PC_CURL_FOUND}" STREQUAL "1")
		find_library(CURL_LIBRARIES NAMES ${PC_CURL_LIBRARIES} PATHS ${PC_CURL_LIBRARIES_DIRS})
		list(APPEND LOCAL_INCLUDE "${PC_CURL_INCLUDE_DIRS}")
		list(APPEND LOCAL_LIBS pstd proto "${CURL_LIBRARIES}")
	else("${PC_CURL_FOUND}" STREQUAL "1")
		message("Missing libcurl, network.http.client servlet won't build")
		set(build_network_http_client "no")
	endif("${PC_CURL_FOUND}" STREQUAL "1")
	set(INSTALL yes)
else("${SYSNAME}" STREQUAL "Linux")
	message("FIXME: network.http.client servlet only support Linux")
	set(build_network_http_client "no")
endif("${SYSNAME}" STREQUAL "Linux")
